"""Backend abstraction: every read/act operation the sentinel and agent perform
goes through a Backend, so the eval harness can replay captured incidents by
swapping LiveBackend for ReplayBackend."""
from __future__ import annotations

from typing import Any, Protocol


class Backend(Protocol):
    # --- docker ---
    def docker_ps(self) -> list[dict[str, Any]]: ...
    def container_logs(self, name: str, lines: int = 100) -> str: ...
    def container_inspect(self, name: str) -> dict[str, Any]: ...
    def container_restart(self, name: str) -> str: ...

    # --- system ---
    def disk_usage(self, paths: list[str]) -> list[dict[str, Any]]: ...
    def du_summary(self, path: str, depth: int = 1) -> str: ...
    def memory(self) -> dict[str, Any]: ...

    # --- transmission ---
    def torrents(self) -> list[dict[str, Any]]: ...
    def remove_torrents(self, ids: list[int], delete_data: bool = False) -> str: ...

    # --- sonarr / radarr ---
    def arr_queue(self, app: str) -> list[dict[str, Any]]: ...
    def arr_blocklist_and_research(self, app: str, queue_ids: list[int]) -> str: ...

    # --- network ---
    def check_urls(self, urls: list[str]) -> list[dict[str, Any]]: ...

    # --- files (Tier 2 territory) ---
    def list_dir(self, path: str) -> list[dict[str, Any]]: ...
    def delete_paths(self, paths: list[str]) -> str: ...
